### ISSUE TITLE
How to template shorty?

### ISSUE THREAD

**Issue by arm2arm** [owncloud/shorty#126]
Hi,
Is any templating  involved currently?
Should I edit directly code?
thanks!

**Comment by arkascha** [comment]
Hi again...
Shorty does not implement any template system, no. 
Feel free to modify it to your needs. 

But be warned: this app is not maintained any longer. It is abandoned. Maybe I was not explicit enough about that in my reply to issue #125. I know, this is never a good thing. But on the other hand I had enough frustration because of that owncloud stuff. The idea behind owncloud is a good one. The way the community is handled by the core team is a joke.

**Comment by arm2arm** [comment]
:) This is always the case with the "young" community.
I hope the things will be better after 8.1, the core looks like more stable.
My plugins also in the low priority in my todo list, because of that, as you mentioned in #125 .
at the institute my users  are loving your plugin.The QR function is appear time by time on the posters:)
Thanks a lot for your effort to bring it to OC8.

**Comment by arkascha** [comment]
Thanks :-)
However: shorty never really arrived at OC-8... I did port it, it was a huge effort and it aws clear from the beginning, that this can only be a temporary step. However when OC-8 finally arrived it turned out that *none* of the third-party apps from the app store could be installed the way people expect: by enabling them in the app selection. Instead you had to install the manually which simply is not possible for many users. And why? Because the core team not even realized that this was broken. So it did not get fixed or anything. No. I was told: "OK, but this is just third party apps". WTF?
Then, when this was finally fixed in OC-8.0.3 now the registration of these apps is broken, so they are mostly useless. Again: getting fixed? No... 

You see this is not about a "young community" as you wrote. There simply is next to no community since many of the contributors left out of frustration. The core team makes it pretty clear again and again that contributions have no priority whatsoever. ownCloud is not a community project. It is a project run by a company that only claims to be backed by an open community. But that simply is not really the case. It is mostly marketing. 

If users at your institute really use the Shorty app, which sounds fine, then I wonder how they do, since it is broken...

**Comment by arm2arm** [comment]
I was wrong with templating :) 
If you make correct theme the relay page looks like this:
![shorty](https://cloud.githubusercontent.com/assets/2283443/7980553/c5f20a12-0aa8-11e5-8d50-918f559e2e34.png)

**Comment by jospoortvliet** [comment]
@arkascha "The core team makes it pretty clear again and again that contributions have no priority whatsoever. ownCloud is not a community project. It is a project run by a company that only claims to be backed by an open community. But that simply is not really the case. It is mostly marketing."

I understand your frustration and this is something we have to improve - and for 8.1, it is being worked on. The problems with the app store and the porting have been frustrating for everybody.

But your statement just makes no sense. as you can see if you analyze github, or look at graphs like http://projects.bitergia.com/ownCloud/browser/ you see that there are more monthly contributors than ownCloud has as employees in TOTAL (including marketing, sales and others who never touch git)...

**Comment by arkascha** [comment]
@jospoortvliet Looks like we agree on most things here. Especially your phrasing "But that simply is not really the case. It is mostly marketing." is _exactly_ what I expressed. 

About the sense of my statement: let's put it that way: for me, a community in the sense of an Open Source project means _lots_ of contributors and a small kernel of payed people taking care or organizational and core issues. This is what I did read in the marketing slogans too (though indeed not that frequent any more...). But to declare that my statement "just makes no sense" and to reason that is because the number of payed programmers is lower than the number of non-payed contributors - come on...

**Comment by arkascha** [comment]
@jospoortvliet Sorry, please don't get this wrong... This is not somehow meant against members of the core team or anything. I just expressed my feelings about the situation contributors are in. 

Just to show the issue, such discrepancies create: 
my company just yesterday dropped owncloud from the range of candidates considered as a base for an addon we plan to offer to our customers. One of the main reasons lined out was serious doubt in the long term development, stability and usability due to a lack in community grip and therefore interest and acceptance in the IT family. Sad, it was me who originally brought owncloud into play, but I can fully support that decision.

**Comment by jospoortvliet** [comment]
I'd love to hear what you see are showing "a lack in community grip and therefore interest and acceptance in the IT family"...  We have over 130 registrations for the ownCloud Contributor Conference already, that's up from 60 registrations we had by July last year - if community is doing so bad, what are all these people doing with ownCloud?

And I'm not sure what you see as 'core team' vs 'contributors', what is the difference, what do you define as 'core team' and what as 'contributor'?

I'm not offended or anything but I'm really interested in finding out what you think is wrong so I can see if it can be fixed. From all I see, ownCloud continues to grow like crazy, we have almost 2 dozen new contributors each month, downloads go up, users are happier and happier. Yes, there are issues and we work on solving them, but nothing that seems to be a barrier to further growth.

**Comment by jospoortvliet** [comment]
@arkascha btw your comment https://github.com/owncloud/shorty/issues/126#issuecomment-110356406 -> I was quoting you, not agreeing with you. You wrote:

* The core team makes it pretty clear again and again that contributions have no priority whatsoever.

I'd love to find out where you see that as I only see people working hard on making ownCloud better, fixing bugs users report, trying to find time for reviewing pull requests from outsiders etc.

* It is a project run by a company that only claims to be backed by an open community.

That I call nonsense. If ownCloud was run only by the company an there was no open community, how come we have 130 people coming to the conference? How come we have over 80 people contributing each month, even though the company has only about 25 engineers? How on earth can you call this NOT a open community? How more open can it be?

Tell me why you get this impression of no community and I can see if there is something I can do.

**Comment by arkascha** [comment]
@jospoortvliet  Let us not start a stupid war over single details, especially since this certainly is not the right place for this. Yes, you are right that it was me who wrote a negative comment here in the first place. But please understand that this was certainly not  meant as a public comment, but a reply to another contributor I know in person. 

About the success in growing the community...
I understand that you probably invest a lot of effort into the project which is a great thing. However that does not automatically turn a project in a working, community backed project. IIRC then the first of such gatherings back in Berlin in (I think) 2009 gathered about 60 people. So in 6 years the project managed to double to number of unpayed contributors, assuming that you are not counting spouses and children which are also openly invited. That is not a thriving and growing community, sorry. 

But all that is not the point. I invested month of work into apps. Apps that helped the product to get recognized. Apps that helped the company to earn money. I never received a real "thanks" for that, actually. Twice some "great" on IRC, but that's about it. Many of my bug reports stayed open for month, some even for years. Which meant I had to invest more time to implement workarounds. Direct questions were more than once answered along the line "no prority, since no core apps are affected" which lead me to some statements that apparently offended. Sorry for that, but it is simply my experience. 
An example from the near past: installing apps the normal way (by clicking on apps offered in the "apps" section where the apps from apps.owncloud.com should be offered was (again) broken in OC-8. When was it fixed? AFAICS not in 8.0.1, not in 8.0.2. not not in month. Sure, the "core apps" (why that distinction, why are some apps in a community project preferred?) were not affected, since they are bundled (again: why?). Then, when the issue was finally fixed in 8.0.3 the registration of legacy apps was broken. AFAICS that is still not fixed, so apps using the legacy way of registering public and remote services cannot be installed properly. I know that this strategy is deprecated. But that does not mean it should not work any more. Apparently that was never tested. Such things lead to comments like my "tired of having to fix issues with each minor release where I again have to implement workarounds". Sure, a harsh criticism. But wrong? Why?

I wish the project a good future. Since I think it is an important project. 
But I also wish that contributors would receive more assistance. 
I will post a message tomorrow to point out that my apps are to be considered discontinued and broken. The same will be posted to the apps entries on apps.owncloud com, to prevent people from using them. 
I think it would make sense to delete the code and remove the entries from apps.owncloud.com, since they miss lead. But that is obviously not my decision. I can only advise in the interest of transparency. 

I hope the event in Berlin is a success! 
arkascha

**Comment by jospoortvliet** [comment]
@arkascha first, two links:
* what we are working on in ownCloud 8.1: https://doc.owncloud.org/server/8.1/developer_manual/general/publishing.html
* and the why: http://karlitschek.de/2015/06/building-a-platform/

Neither of the above are decisions by the company or have anything to do with it.

I won't say any of the bad things you mention don't happen. They are sad and frustrating but it happened exactly **because ownCloud is a community project**. People can make their own choices, set their own priorities and you don't get to tell them what to do unless you pay them.

How exactly is it the fault of the company, that I don't get. We are one of the contributors to the ownCloud community and we work on the features and improvements our customers want. 

You seem to think that 'ownCloud Inc' decides who works on what and when - but we only decide that for the two dozen people who we pay. Last year, about 350 people contributed to ownCloud, and they did whatever **THEY** wanted. If stuff that you want doesn't get done, it is because nobody felt like doing it, nobody got paid for it and you didn't do it either.

Now I agree that, because the company does a lot of work in ownCloud and we get help from volunteers like you, we should put in some extra effort in maintaining ownCloud. We do. We pay for the conference, marketing, web servers and of course we write a lot of code. Much bugfixing and most work on keeping older releases stable is done by us. And we try to do more. Many asked for that in the survey I did in January and we'll announce some of what we're doing in response at the conference. But in the end - we are simply paid by customers to improve ownCloud and that is what we do. **We can't do everything**.

And yes, it would be nice to get a thanks occasionally. But that - too - it's not something the company should do. You're not contributing to ownCloud, Inc. but you contribute to ownCloud, which is **YOURS**. It is open source, community owned. If your users thank you (and they should) that is *awesome*. And we, at Inc, are happy to be part of ownCloud and yes, we're happy if people develop cool apps. Because it helps make ownCloud better for more users. But you shouldn't contribute to help ownCloud, Inc. unless you get paid by it! You should contribute for yourself, for your friends, family, users, for the fun of it, because you want to *help users get their data back*.




By the way, I kind of doubt there was a big ownCloud gathering in Berlin in 2009 - ownCloud was announced in 2010 by Frank (I was there in San Diego when he talked about the need for something like ownCloud) and the first Berlin meeting at the TU was in 2013 and had about 30-40 people. Before that, the co-working spaces in Nuremberg and Stuttgart were used for meetings, I believe.

**Comment by arkascha** [comment]
@jospoortvliet Such naïveté does not require further discussions :-)
Have fun in your dream world!

**Comment by jospoortvliet** [comment]
Fair enough.
